#-------------------------------
# General Site Settings

title: Tauke
logo: 
author: taukedev
description: Platform Penanaman Modal Untuk Panen Petani
email: toke@tauke.id
phone: +62 8123456789
address: Siantar, North Sumatra, Indonesia
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: Tentang, link: '/tauke/about'}
- {name: Blog, link: '/tauke/blog'}
- {name: Proyek, link: '/tauke/portfolio'}
- {name: Kontak, link: '/tauke/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Sukseskan Panen Petani <br> Bersama <br> Tauke Indonesia

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Platform P2P lending yang mendanai tengkulak untuk membeli hasil panen petani dan membantu petani memperoleh harga panen yang lebih baik.


blurb-btn-link: '/tauke/about'
blurb-btn-name: Tentang Tauke Selengkapnya


# About Page

# Work Process Section
work-process:
  - title : "Mitra Tengkulak"
    icon : "assets/images/icons/plan.png"
    content : "Mitra trader membantu menjualkan hasil panen dengan mengambil proyek panen yang kami tawarkan. Mitra trader juga dapat menawarkan proyek panen Kepada tauke."
    
  - title : "Taukefund"
    icon : "assets/images/icons/design.png"
    content : "Platform yang mensupport untuk mendanai proyek panen yang dilakukan oleh Tengkulak dengan sistem investasi per proyek panen."
    
  - title : "Mitra Tani"
    icon : "assets/images/icons/print.png"
    content : "Mitra tani kami sebagai supplier menawarkan proyek panen kepada tauke."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Web Design, color: '#fdb157', value: '90%'}
- {name: Logo Design, color: '#9473e6', value: '60%'}
- {name: After Effects, color: '#bdecf6', value: '80%'}
- {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
- {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

services-title: Layanan Tauke
services:
- {
    name: Penanaman Modal,
    icon: ti-palette,
    description: 'Masyarakat dapat berinvestasi per proyek panen. Investasi yang ditawarkan tauke selain menjanjikan Return of Investment yang menarik juga membuka kesempatan untuk berinvestasi dengan tagar #PendanaanBerdampakSosial kepada petani Indonesia.',
    active: # Add true to select section
  }
- {
    name: Logistik,
    icon: ti-vector,
    description: 'Layanan pengiriman barang dan ekspedisi tauke yang dapat melayani banyak rute pengiriman barang di Indonesia.',
    active: # Add true to select section
  }
- {
    name: E-commerce Produk Pertanian,
    icon: ti-panel,
    description: 'Layanan pemesanan dan pembelian hasil panen langsung dari petani.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "Penanaman Modal",
    type : "design"
  }
- {
    title : "Logistik",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation : "CEO, Funder"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Info Kontak
contact-email: toke@tauke.id
